//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUserSeen
    {
        public int AUserSeenID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MovieID { get; set; }
    
        public virtual AMovie AMovie { get; set; }
        public virtual AUser AUser { get; set; }
    }
}
