//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUser_Previous_Bought_Snacks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUser_Previous_Bought_Snacks()
        {
            this.AUsers = new HashSet<AUser>();
        }
    
        public int AUserPBSID { get; set; }
        public Nullable<int> SnacksID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUser> AUsers { get; set; }
        public virtual Snacks_Selling Snacks_Selling { get; set; }
    }
}
