//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPlayDKEntities : DbContext
    {
        public BPlayDKEntities()
            : base("name=BPlayDKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMovie> AMovies { get; set; }
        public virtual DbSet<AUser> AUsers { get; set; }
        public virtual DbSet<AUser_Previous_Bought_Snacks> AUser_Previous_Bought_Snacks { get; set; }
        public virtual DbSet<AUserSeen> AUserSeens { get; set; }
        public virtual DbSet<AUserType> AUserTypes { get; set; }
        public virtual DbSet<Bought_Snacks> Bought_Snacks { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<MoviePlaying> MoviePlayings { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Snacks_Selling> Snacks_Selling { get; set; }
    }
}
