//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviePlaying
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoviePlaying()
        {
            this.Cinemas = new HashSet<Cinema>();
            this.Seats = new HashSet<Seat>();
        }
    
        public int MovieplayingID { get; set; }
        public Nullable<int> SeatsID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<System.DateTime> DatePlaying { get; set; }
        public Nullable<System.DateTime> TimePlaying { get; set; }
    
        public virtual AMovie AMovie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cinema> Cinemas { get; set; }
        public virtual Seat Seat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
