//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.AUsers = new HashSet<AUser>();
        }
    
        public int ReservationID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CinemaID { get; set; }
        public Nullable<int> SeatsID { get; set; }
        public Nullable<int> BoughtSnacksID { get; set; }
    
        public virtual AMovie AMovie { get; set; }
        public virtual AMovie AMovie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUser> AUsers { get; set; }
        public virtual AUser AUser { get; set; }
        public virtual Bought_Snacks Bought_Snacks { get; set; }
        public virtual Cinema Cinema { get; set; }
    }
}
