//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat()
        {
            this.MoviePlayings = new HashSet<MoviePlaying>();
        }
    
        public int SeatsID { get; set; }
        public Nullable<int> CinemaID { get; set; }
        public Nullable<int> MoviePlayingID { get; set; }
        public Nullable<bool> Reserved { get; set; }
        public string SeatIdentity { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviePlaying> MoviePlayings { get; set; }
        public virtual MoviePlaying MoviePlaying { get; set; }
    }
}
