//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseConnection.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snacks_Selling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Snacks_Selling()
        {
            this.AUser_Previous_Bought_Snacks = new HashSet<AUser_Previous_Bought_Snacks>();
        }
    
        public int SnackID { get; set; }
        public string Snacks_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUser_Previous_Bought_Snacks> AUser_Previous_Bought_Snacks { get; set; }
    }
}
